"""Pydantic Request & Response Schemas for Server Endpoints.

Defines strongly-typed data validation models for all REST & SSE streaming
endpoints in the FastAPI web application.
"""

from typing import List, Dict, Optional
from pydantic import BaseModel, Field


class ChatStreamRequest(BaseModel):
    """Payload schema for POST /api/chat/stream endpoint."""

    prompt: str = Field(
        ...,
        description="The user input message or question."
    )
    model: str = Field(
        default="groq/qwen/qwen3.8-27b",
        description="Target model engine slug (e.g. 'groq/qwen/qwen3.8-27b', 'gemini/gemma-4-31b-it')."
    )
    session_id: str = Field(
        default="default-session",
        description="Correlation ID mapping requests to chat sessions in Langfuse."
    )
    guardrails_enabled: bool = Field(
        default=True,
        description="Flag indicating whether NeMo Guardrails safety filtering is applied."
    )
    history: List[Dict[str, str]] = Field(
        default=[],
        description="List of prior conversation turns for multi-turn conversational context."
    )


class TranscribeResponse(BaseModel):
    """Response schema for POST /api/transcribe voice speech-to-text endpoint."""

    text: str = Field(
        ...,
        description="Transcribed text string generated by Groq Whisper Turbo."
    )
    duration_s: float = Field(
        ...,
        description="Total duration in seconds taken by the transcription model."
    )
