"""State Schema for the Agentic Marketing Campaign Workflow.

Defines the centralized TypedDict state container passed across the
LangGraph marketing state machine nodes (Researcher, Strategist, Copywriter, Critic, Publisher).
"""

from typing import List, Dict, Any, Optional
from typing_extensions import TypedDict


class MarketingCampaignState(TypedDict):
    """Centralized state schema for multi-agent marketing campaign generation."""

    # 1. Input Brief & Parameters
    brief: str
    """User product brief, value proposition, and campaign objectives."""

    product_name: str
    """Extracted or specified product/service name."""

    target_audience: str
    """Target demographic/persona (e.g. 'B2B Enterprise CTOs', 'Indie Developers')."""

    brand_voice: str
    """Target brand tone (e.g. 'Authoritative & Technical', 'Energetic & Direct')."""

    target_channels: List[str]
    """Channels to produce copy for (e.g. ['twitter', 'linkedin', 'email', 'blog'])."""

    session_id: str
    """Correlation trace identifier for Langfuse."""

    # 2. Safety & Guardrails
    guardrail_allowed: bool
    """True if marketing brief passed brand safety checks, False if blocked."""

    guardrail_reason: str
    """Explanatory reason for guardrail approval or security block."""

    # 3. Market Research & Strategy
    research_insights: List[str]
    """Audience pain points, competitor positioning, and trend hooks gathered by Researcher."""

    campaign_angles: List[Dict[str, str]]
    """Strategic angles, viral hooks, and themes formulated by Strategist."""

    # 4. Copy Assets & Reflection
    copy_drafts: Dict[str, str]
    """Generated copy keyed by channel (e.g. {'twitter': '...', 'linkedin': '...'})."""

    critic_feedback: List[str]
    """Critique notes and revision instructions generated by Critic Agent."""

    critic_approved: bool
    """True if copy meets strict length, readability, and brand quality gates."""

    revision_count: int
    """Number of self-correction reflection loops executed."""

    # 5. Final Package
    final_campaign: Dict[str, Any]
    """Final validated, ready-to-publish campaign deliverables."""
