"""LangGraph Autonomous Research Agent State Schema.

This module defines `ResearchState`, the centralized state container that flows
across all nodes in the LangGraph state machine.

State Properties:
    - query: Sanitized user research question.
    - session_id: Unique trace correlation session identifier.
    - guardrail_allowed: Boolean indicating if the prompt passed safety filters.
    - guardrail_reason: Policy justification if blocked or flagged.
    - plan_steps: Ordered list of decomposed research steps generated by the Planner.
    - findings: Evidence gathered from tool executions (search snippets, calculations).
    - final_report: Comprehensive executive synthesis generated by the Synthesizer.
    - iteration_count: Guard to prevent infinite graph recursion.
"""

from typing import List, Dict, Any, Optional
from typing_extensions import TypedDict


class ResearchState(TypedDict):
    """Centralized state schema passed between LangGraph workflow nodes."""

    query: str
    """The sanitized user input query being researched."""

    session_id: str
    """Unique session identifier correlating logs, traces, and UI sessions."""

    guardrail_allowed: bool
    """True if input passed NeMo Guardrails safety policies, False otherwise."""

    guardrail_reason: str
    """Explanatory reason for guardrail approval or security rejection."""

    plan_steps: List[Dict[str, str]]
    """Structured execution steps planned by the LLM Planner node (e.g. [{'tool': 'web_search', 'input': '...'}])."""

    findings: List[Dict[str, str]]
    """Empirical evidence and results gathered from executed tools."""

    final_report: str
    """Executive synthesized markdown report compiled from gathered findings."""

    iteration_count: int
    """Counter tracking agent execution cycles to enforce max step limits."""
